### PR TITLE
Steven's suggested edits for section 1

### PR DESCRIPTION
**Pull request by bamford**
Does supplying edits like this work?  The inline highlighting appears to give up on long lines, which might make it difficult to see the changes.

Further sections to follow as additional pull requests.

### CODE REVIEW

**Comment by willettk** [comment]
It's not ideal for long prose, I agree - might be a reason for me to move to line breaks in my actual writing (or something like Authorea or Overleaf, which handle this a bit better). But let's try regular PRs and see if we can make it work. Thanks!

**Comment by bamford** [comment]
My comments on section 2 are accumulating here: https://github.com/willettk/gzhubble/issues/89

Sorry for mixing methods!

**Comment by bamford** [comment]
Just found `git diff --color-words`, which will make understanding the changes much easier! cc #90

**Comment by willettk** [comment]
My regular diff setup highlights the changes pretty well in the terminal on my local machine, although it's still not easy to see in Github. I think I might reformat the manuscript to have actual line breaks at roughly 80 characters so this sort of thing is easier.

**Pull request merged**
