### PR TITLE
added specz flag to dropbox metadata tables and explanation text in s…

### PR DESCRIPTION
**Pull request by Mel23**
…ec 2.5

### CODE REVIEW

**Comment by willettk** [comment]
Addresses issues in #79.

**Comment by willettk** [comment]
This is good, @Mel23. A couple small changes requested:
- change the name of column from `z_spec_flag` to `z_spec_conflict_flag` (or something similar; we want it clear from the description that this is for galaxies where measurements don't exist)
- instead of floats (0. or 1.), please set flag as boolean values (True or False) in Python. That makes it easier to use in TOPCAT because it's immediately useable as a row subset.
- what was your criteria for setting the flag? Should go in descriptions of tables (see #53).

**Comment by willettk** [comment]
In the tables it also looks like the fraction of conflicting spec-z's is 3% of GOODS 5-epoch images, 6% of GOODS 2-epoch images, and 0.05% of the main sample (AEGIS, COSMOS, GEMS). Do those numbers check out with you, @Mel23? And why is the fraction so much higher for GOODS compared to the other Legacy surveys?

**Comment by Mel23** [comment]
To your comments @willettk: 
- done, good point. 
- also done. 
- criteria for setting the flag is described in section 2.5

-Yes the numbers check out - there are more discrepancies in the GOODS data because, of the 3 catalogs with specz, MUSYC _only_ had data for GEMS + GOODS. So for these surveys, specz's may have potential discrepancies between 3 catalogs instead of 2, increasing the likelihood of a discrepancy.

**Pull request merged**
