### PR TITLE
Fixing filter curves for GOODS 5-epoch. See #91.

### PR DESCRIPTION
**Pull request by willettk**

### CODE REVIEW

**Comment by willettk** [comment]
I'm confused now; I thought #91 meant you wanted me to use something different than http://www.stsci.edu/hst/acs/analysis/throughputs/tables ?

**Comment by vrooje** [comment]
I downloaded the ACS WFC F850LP data from that page and got the plot I posted on #91 - that's not what currently shows in the committed figure, right?

**Comment by willettk** [comment]
I think it's fixed now; I got all of the filters from the SVO and they look consistent. @vrooje, please take a look at the new figure and let me know what you think. If it's good, I'll handle the merge since I stupidly added the PDF again.

**Comment by vrooje** [comment]
👍 I think this is good to go now.

**Pull request merged**
